package br.com.orcamento3d.gcode;

import org.junit.jupiter.api.Test;
import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import static org.assertj.core.api.Assertions.assertThat;

class GcodeAnalyzerTest {
    private final GcodeAnalyzer analyzer = new GcodeAnalyzer();

    @Test
    void analyzesAbsoluteExtrusionAndMovementTime() throws Exception {
        String gcode = """
                G90
                M82
                G1 X60 Y0 F1200
                G1 X60 Y60 E10 F600
                G1 X0 Y60 E20
                """;
        GcodeAnalysis result = analyzer.analyze(stream(gcode));
        assertThat(result.lineCount()).isEqualTo(5);
        assertThat(result.printTimeMinutes()).isCloseTo(0.25, within(0.001));
        assertThat(result.filamentMillimeters()).isEqualTo(20);
        assertThat(result.filamentGrams()).isBetween(0.05, 0.07);
    }

    @Test
    void supportsRelativeExtrusion() throws Exception {
        GcodeAnalysis result = analyzer.analyze(stream("M83\nG1 E5 F300\nG1 E3\nG1 E-1\n"));
        assertThat(result.filamentMillimeters()).isEqualTo(8);
    }

    @Test
    void prefersSlicerTimeMetadata() throws Exception {
        GcodeAnalysis result = analyzer.analyze(stream(";TIME:3600\nG1 X10 F600\n"));
        assertThat(result.printTimeMinutes()).isEqualTo(60);
    }

    @Test
    void readsCrealityOrOrcaHumanTimeAndFilamentWeight() throws Exception {
        String gcode = """
                ; estimated printing time (normal mode) = 8h 7m
                ; total filament used [g] = 68.89
                G1 X10 E.125 F600
                """;
        GcodeAnalysis result = analyzer.analyze(stream(gcode));
        assertThat(result.printTimeMinutes()).isEqualTo(487);
        assertThat(result.filamentGrams()).isEqualTo(68.89);
        assertThat(result.filamentMillimeters()).isGreaterThan(20_000);
    }

    @Test
    void sumsMultimaterialFilamentWeights() throws Exception {
        GcodeAnalysis result = analyzer.analyze(stream(
                "; filament used [g] = 20.5, 48.39\n"));
        assertThat(result.filamentGrams()).isEqualTo(68.89);
    }

    @Test
    void acceptsLongOrcaExcludeObjectLineAndReadsTrailingMetadata() throws Exception {
        String longPolygon = "EXCLUDE_OBJECT_DEFINE NAME=blade CENTER=1,1 POLYGON=["
                + "1,1,".repeat(2_600) + "]\n";
        String gcode = longPolygon + """
                ; generated by Creality_Print V7.2.0.5226 on [year]-[month]-[day] at [hour]:[minute]:[second]\\n; total layer number: 885
                ; filament used [mm] = 39930.82, 0.00, 0.00, 0.00
                ; filament used [g] = 120.06, 0.00, 0.00, 0.00
                ; estimated printing time (normal mode) = 5h 35m 54s
                ; filament_colour = #FFFFFF;#FF614B;#FFFFFF;#8A43FF
                ; filament_settings_id = "Soleyin Ultra PLA BRANCO";"Generic PETG";"Generic ABS";"Generic PLA"
                ; filament_type = PLA;PETG;ABS;PLA
                ; printer_model = Creality K2
                ; printer_settings_id = Creality K2 0.4
                """;

        GcodeAnalysis result = analyzer.analyze(stream(gcode));

        assertThat(result.printTimeMinutes()).isCloseTo(335.9, within(0.001));
        assertThat(result.filamentGrams()).isEqualTo(120.06);
        assertThat(result.slicer()).isEqualTo("Creality Print");
        assertThat(result.printerModel()).isEqualTo("Creality K2");
        assertThat(result.filaments()).first().satisfies(filament -> {
            assertThat(filament.material()).isEqualTo("PLA");
            assertThat(filament.grams()).isEqualTo(120.06);
        });
    }

    private ByteArrayInputStream stream(String value) {
        return new ByteArrayInputStream(value.getBytes(StandardCharsets.UTF_8));
    }
    private static org.assertj.core.data.Offset<Double> within(double value) {
        return org.assertj.core.data.Offset.offset(value);
    }
}
