package br.com.orcamento3d.gcode;

import org.springframework.stereotype.Service;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.Locale;
import java.util.regex.*;

@Service
public class GcodeAnalyzer {
    // OrcaSlicer pode gerar EXCLUDE_OBJECT_DEFINE com milhares de pontos em uma
    // única linha. Essas linhas são válidas e não devem interromper a leitura
    // dos metadados que ficam no fim do arquivo.
    private static final int MAX_GCODE_LINE_LENGTH = 1_000_000;
    private static final Pattern PARAM = Pattern.compile(
            "([XYZEF])\\s*(-?(?:\\d+(?:\\.\\d*)?|\\.\\d+)(?:[Ee][+-]?\\d+)?)",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern SECONDS_TIME = Pattern.compile(
            "(?:^|;)\\s*(?:TIME|PRINT_TIME)\\s*[:=]\\s*(\\d+(?:\\.\\d+)?)",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern HUMAN_TIME = Pattern.compile(
            "estimated printing time[^=]*=\\s*(?:(\\d+)d\\s*)?(?:(\\d+)h\\s*)?(?:(\\d+)m\\s*)?(?:(\\d+)s)?",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern FILAMENT_GRAMS = Pattern.compile(
            "(?:total\\s+)?filament(?:\\s+used|\\s+weight)?\\s*\\[g(?:rams?)?]\\s*=\\s*([\\d.,\\s]+)",
            Pattern.CASE_INSENSITIVE);
    private static final double FILAMENT_DIAMETER_MM = 1.75;
    private static final double PLA_DENSITY_G_CM3 = 1.24;
    private static final Pattern MAGNET_COUNT = Pattern.compile(
            "(?:ORCAPRINT_)?MAGNET(?:_COUNT)?\\s*[:=]\\s*(\\d+)", Pattern.CASE_INSENSITIVE);
    private static final Pattern FILAMENT_TYPE = Pattern.compile(
            "(?:filament_type|filament material)\\s*=\\s*(.+)$",Pattern.CASE_INSENSITIVE);
    private static final Pattern FILAMENT_COLOR = Pattern.compile(
            "filament_(?:colour|color)\\s*=\\s*(.+)$",Pattern.CASE_INSENSITIVE);
    private static final Pattern KEY_VALUE = Pattern.compile("^;\\s*([^:=]+?)\\s*[:=]\\s*(.*?)\\s*$");
    private static final Pattern GENERATED = Pattern.compile(
            "generated by\\s+(.+?)(?=\\s+on\\s+|\\\\[rn]|$)", Pattern.CASE_INSENSITIVE);

    public GcodeAnalysis analyze(InputStream input) throws IOException {
        long lines = 0;
        double x = 0, y = 0, z = 0, e = 0, feed = 1800;
        double seconds = 0, filament = 0;
        boolean absolutePosition = true, absoluteExtrusion = true;
        Double slicerSeconds = null;
        Double slicerGrams = null;
        boolean magnetInsertion = false;
        int magnetCount = 0;
        String filamentMaterial=null,filamentColor=null,filamentProfiles=null;
        String printerModel=null,printerProfile=null,slicer=null;
        double nozzleDiameter=0,bedWidth=0,bedDepth=0,printableHeight=0,modelHeight=0;
        double nozzleTemperature=0,bedTemperature=0;
        int layerCount=0;
        List<Double> metadataGramsList=List.of(),metadataMillimetersList=List.of();

        try (var reader = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8))) {
            String raw;
            while ((raw = reader.readLine()) != null) {
                lines++;
                if (raw.length() > MAX_GCODE_LINE_LENGTH)
                    throw new IOException("Linha de G-code excessivamente longa");
                Double metadataTime = parseTime(raw);
                if (metadataTime != null && metadataTime > 0) slicerSeconds = metadataTime;
                Double metadataGrams = parseGrams(raw);
                if (metadataGrams != null && metadataGrams > 0) slicerGrams = metadataGrams;
                Matcher generated=GENERATED.matcher(raw);
                if(generated.find())slicer=slicerName(cleanMetadata(generated.group(1)));
                Matcher keyValue=KEY_VALUE.matcher(raw);
                if(keyValue.matches()){
                    String key=keyValue.group(1).trim().toLowerCase(Locale.ROOT),value=keyValue.group(2).trim();
                    switch(key){
                        case "printer_model" -> printerModel=cleanMetadata(value);
                        case "printer_settings_id" -> printerProfile=cleanMetadata(value);
                        case "filament_settings_id" -> filamentProfiles=value;
                        case "nozzle_diameter" -> nozzleDiameter=firstNumber(value);
                        case "printable_height" -> printableHeight=firstNumber(value);
                        case "max_z_height" -> modelHeight=firstNumber(value);
                        case "total layer number","total layers count" -> layerCount=(int)firstNumber(value);
                        case "nozzle_temperature" -> nozzleTemperature=maxNumber(value);
                        case "first_layer_bed_temperature" -> bedTemperature=firstNumber(value);
                        case "bed_shape","printable_area" -> {
                            double[] size=areaSize(value);if(size[0]>0){bedWidth=size[0];bedDepth=size[1];}
                        }
                        case "filament used [g]" -> metadataGramsList=numbers(value);
                        case "filament used [mm]" -> metadataMillimetersList=numbers(value);
                    }
                }
                Matcher magnet = MAGNET_COUNT.matcher(raw);
                if (magnet.find()) { magnetInsertion = true; magnetCount = Math.max(magnetCount,Integer.parseInt(magnet.group(1))); }
                String upperRaw=raw.toUpperCase(Locale.ROOT);
                if ((upperRaw.contains("MAGNET")||upperRaw.contains("ÍMÃ")) &&
                        (upperRaw.contains("PAUSE")||upperRaw.matches(".*\\bM(?:0|25|600|601)\\b.*"))) magnetInsertion=true;
                if(filamentMaterial==null){Matcher fm=FILAMENT_TYPE.matcher(raw);if(fm.find())filamentMaterial=cleanMetadata(fm.group(1));}
                if(filamentColor==null){Matcher fc=FILAMENT_COLOR.matcher(raw);if(fc.find())filamentColor=cleanMetadata(fc.group(1));}
                String line = raw.split(";", 2)[0].trim().toUpperCase(Locale.ROOT);
                if (line.equals("G90")) { absolutePosition = true; continue; }
                if (line.equals("G91")) { absolutePosition = false; continue; }
                if (line.equals("M82")) { absoluteExtrusion = true; continue; }
                if (line.equals("M83")) { absoluteExtrusion = false; continue; }
                if (line.startsWith("G92")) {
                    Matcher m = PARAM.matcher(line);
                    while (m.find()) {
                        double value = Double.parseDouble(m.group(2));
                        switch (m.group(1).charAt(0)) {
                            case 'X' -> x = value; case 'Y' -> y = value;
                            case 'Z' -> z = value; case 'E' -> e = value;
                        }
                    }
                    continue;
                }
                if (!(line.matches("^G0?0\\s+.*") || line.matches("^G0?1\\s+.*"))) continue;

                Double nx = null, ny = null, nz = null, ne = null, nf = null;
                Matcher m = PARAM.matcher(line);
                while (m.find()) {
                    double value = Double.parseDouble(m.group(2));
                    switch (m.group(1).charAt(0)) {
                        case 'X' -> nx = value; case 'Y' -> ny = value;
                        case 'Z' -> nz = value; case 'E' -> ne = value; case 'F' -> nf = value;
                    }
                }
                if (nf != null && nf > 0) feed = nf;
                double tx = nx == null ? x : (absolutePosition ? nx : x + nx);
                double ty = ny == null ? y : (absolutePosition ? ny : y + ny);
                double tz = nz == null ? z : (absolutePosition ? nz : z + nz);
                double distance = Math.sqrt(sq(tx - x) + sq(ty - y) + sq(tz - z));
                seconds += distance / feed * 60.0;
                if (ne != null) {
                    double delta = absoluteExtrusion ? ne - e : ne;
                    if (delta > 0) filament += delta;
                    e = absoluteExtrusion ? ne : e + ne;
                }
                x = tx; y = ty; z = tz;
            }
        }
        double area = Math.PI * sq(FILAMENT_DIAMETER_MM / 2.0);
        double grams = area * filament / 1000.0 * PLA_DENSITY_G_CM3;
        if (slicerGrams != null) {
            grams = slicerGrams;
            filament = grams / PLA_DENSITY_G_CM3 * 1000.0 / area;
        }
        List<String> materials=splitMetadata(filamentMaterial),colors=splitMetadata(filamentColor),profiles=splitMetadata(filamentProfiles);
        int count=Math.max(1,Math.max(metadataGramsList.size(),Math.max(materials.size(),Math.max(colors.size(),profiles.size()))));
        List<GcodeAnalysis.FilamentMetadata> detected=new ArrayList<>();
        for(int i=0;i<count;i++){
            double detectedGrams=numberAt(metadataGramsList,i),detectedMm=numberAt(metadataMillimetersList,i);
            if(detectedGrams<=0&&i>0)continue;
            if(detectedGrams<=0)detectedGrams=grams;
            if(detectedMm<=0&&detectedGrams>0)detectedMm=detectedGrams/PLA_DENSITY_G_CM3*1000.0/area;
            detected.add(new GcodeAnalysis.FilamentMetadata(textAt(materials,i),colorName(textAt(colors,i)),
                    textAt(profiles,i),detectedGrams,detectedMm));
        }
        return new GcodeAnalysis(lines, (slicerSeconds != null ? slicerSeconds : seconds) / 60.0,
                filament, grams,magnetInsertion,magnetCount,detected,printerModel,printerProfile,slicer,
                nozzleDiameter,bedWidth,bedDepth,printableHeight,modelHeight,layerCount,nozzleTemperature,bedTemperature);
    }

    private Double parseTime(String raw) {
        Matcher seconds = SECONDS_TIME.matcher(raw);
        if (seconds.find()) return Double.parseDouble(seconds.group(1));
        Matcher human = HUMAN_TIME.matcher(raw);
        if (!human.find()) return null;
        long days = number(human.group(1)), hours = number(human.group(2));
        long minutes = number(human.group(3)), secs = number(human.group(4));
        return (double) (days * 86400 + hours * 3600 + minutes * 60 + secs);
    }

    private Double parseGrams(String raw) {
        Matcher matcher = FILAMENT_GRAMS.matcher(raw);
        if (!matcher.find()) return null;
        Matcher values = Pattern.compile("\\d+(?:[.,]\\d+)?").matcher(matcher.group(1));
        double total = 0;
        while (values.find()) total += Double.parseDouble(values.group().replace(',', '.'));
        return total > 0 ? total : null;
    }

    private long number(String value) { return value == null ? 0 : Long.parseLong(value); }
    private String cleanMetadata(String value){String v=value.trim().replace("\"","");return v.isBlank()?null:v;}
    private String slicerName(String value){
        if(value==null)return null;
        String normalized=value.toLowerCase(Locale.ROOT).replace('_',' ');
        if(normalized.contains("orca"))return "OrcaSlicer";
        if(normalized.contains("creality"))return "Creality Print";
        if(normalized.contains("prusa"))return "PrusaSlicer";
        if(normalized.contains("bambu"))return "Bambu Studio";
        if(normalized.contains("ultimaker")||normalized.contains("cura"))return "Ultimaker Cura";
        if(normalized.contains("superslicer"))return "SuperSlicer";
        if(normalized.contains("ideamaker"))return "ideaMaker";
        if(normalized.contains("simplify3d"))return "Simplify3D";
        return value.replaceFirst("\\s+[vV]?\\d+(?:\\.\\d+)+(?:[-.\\w]+)?\\s*$","");
    }
    private double firstNumber(String value){List<Double> n=numbers(value);return n.isEmpty()?0:n.get(0);}
    private double maxNumber(String value){return numbers(value).stream().mapToDouble(Double::doubleValue).max().orElse(0);}
    private List<Double> numbers(String value){List<Double> result=new ArrayList<>();Matcher m=Pattern.compile("-?\\d+(?:\\.\\d+)?").matcher(value);while(m.find())result.add(Double.parseDouble(m.group()));return result;}
    private List<String> splitMetadata(String value){if(value==null||value.isBlank())return List.of();return Arrays.stream(value.split("[;,]")).map(this::cleanMetadata).filter(Objects::nonNull).toList();}
    private double numberAt(List<Double> values,int i){return i<values.size()?values.get(i):0;}
    private String textAt(List<String> values,int i){return i<values.size()?values.get(i):null;}
    private double[] areaSize(String value){List<Double> n=numbers(value);if(n.size()<4)return new double[]{0,0};double minX=Double.MAX_VALUE,maxX=-Double.MAX_VALUE,minY=Double.MAX_VALUE,maxY=-Double.MAX_VALUE;for(int i=0;i+1<n.size();i+=2){minX=Math.min(minX,n.get(i));maxX=Math.max(maxX,n.get(i));minY=Math.min(minY,n.get(i+1));maxY=Math.max(maxY,n.get(i+1));}return new double[]{maxX-minX,maxY-minY};}
    private String colorName(String value){if(value==null)return null;return switch(value.toUpperCase(Locale.ROOT)){case "#FFFFFF"->"Branco";case "#000000"->"Preto";case "#FF0000"->"Vermelho";case "#00FF00"->"Verde";case "#0000FF"->"Azul";case "#FFFF00"->"Amarelo";default->value;};}
    private static double sq(double value) { return value * value; }
}
